# Generated by Django 5.1.7 on 2025-03-30 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('jugador', 'Jugador'), ('maestro', 'Maestro')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('respuesta_correcta', models.CharField(max_length=255)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.sesion')),
            ],
        ),
        migrations.AddField(
            model_name='sesion',
            name='maestro',
            field=models.ForeignKey(limit_choices_to={'rol': 'maestro'}, on_delete=django.db.models.deletion.CASCADE, to='juego.usuario'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.pregunta')),
                ('jugador', models.ForeignKey(limit_choices_to={'rol': 'jugador'}, on_delete=django.db.models.deletion.CASCADE, to='juego.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntas_correctas', models.IntegerField(default=0)),
                ('preguntas_totales', models.IntegerField(default=0)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.sesion')),
                ('jugador', models.ForeignKey(limit_choices_to={'rol': 'jugador'}, on_delete=django.db.models.deletion.CASCADE, to='juego.usuario')),
            ],
        ),
    ]
